title: Tejaswini R
description: Portfolio | Projects | Assistive Technology
theme: jekyll-theme-minimal
## About Me

I am a B.E. undergraduate student in Electronics and Communication Engineering at K S Institute of Technology, Bengaluru, Karnataka. I have a strong interest in embedded systems, assistive technologies, and applying electronics and programming to solve real-world problems.

I am passionate about learning new technologies and actively seek opportunities to enhance my technical skills through hands-on projects and internships. I enjoy working on solutions that are practical, meaningful, and socially impactful.
